language: python
python:
- 3.5
rvm:
- 2.0.0
services:
- docker
before_install:
- gem update --system
- gem --version
- pip3 install dropbox
script:
- export OSGEO4A_SDK=opengisch/qfield-sdk:20190221
- docker pull ${OSGEO4A_SDK}
- docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-${ARCH}" -e "ARCH=${ARCH}"
  -e "VERSION=${TRAVIS_TAG}" ${OSGEO4A_SDK} /usr/src/input/scripts/docker-build.sh
- "./scripts/upload-artifacts.sh"
jobs:
  include:
  - stage: build
    name: build ARMv7
    env:
    - ARCH=armv7
env:
  global:
    secure: "toZa8njDp7uT2PaiCBhabrWcooEn/cLPBte7liBaZAWbsqMlwhKcUALFkBuPBOi13VjG8DUCKF1/RItT0VLyiNIs90DB9czIO48a/AUh85vZcCOFv0z0uU3HqA9eUzTBCh99kNq41btlf6ok262JPkYzjcNWeMv9wPbE1gDzRItbcCsR/wylIGOFFp1LhZJtI/NUrnlZ1N4S4TOYI3xO8obKj28RKgqhuMoKJ1gmEpfyXDaQ5S+7To6bX5G0SFa7HhfAquKMJzI6D+V+IjFi7ZDOEcK1TZVjHAm0PVFJolDZcPNKfMSfg3ykvrktwVEpaJL9lhuVk0IUGwUw67Vr4FhVicZb+wGR/xHP3T6zCSiWLEwGFiKACynhqb4m2CWDhcR9ls5Yani9V7CcIZfmb8bJ1VGgtAKeI1+Ti9BxzLXIyzhACAz3YbeuuQpJ+xXQ3URiu6OA8DPqJRrL83gBOiBbJje+4YPWabIP78CVmbbgvI6xQ+QKBgr7bzOl7RNlmMr3AhohE41KLNdT8+yf1oPaOmnJJH9Ode7vcpo+vHmRN03z7B2480YEeD7uO2aA9suFjGSiMyvXSQExFe0TI9vYvaJf2l2eZgyxNl1/iai1dE/9r9F0ElWJbOIiVgihe/Q7oKXmBk5EiCTyLyM5f1bNSRwQLAga5gtJ9s9KV4U="
    secure: "Fsb/FK9Zw2efl6eUDyYkOFigGkQuuDIkc5H2Qff0o22c/+A6HXKsty9T80qnoqrWj1yFtzbr4X7/3iXcr3QQ0P0dFpd8QiMFNMSM3tjCkmOti/YHwgUnb0HcZyc5SRtqCHJBbfzZ5qAyHLHrBK/RiXqZ+bKLsOYcC7iK14Ott64Gdg8VD1PywTYCj5st2QztQote4DwV8vSue1uKDMrcqlc+VuaevZq7s+tJu49GLyuv8dQvjxqaMT8E9Z4wuNkhjb2JTXyaACp6ooTGwH4I1cDdz7WVFu1gs08UEu6Zdg48P95UjY5LBAVfFDLocPrO3V9U2UxIMlEbbnK58M0Le8SjTipihi30EViurNaMlnZPejfelqICpPM4+lm5okRQKR0ndUJnDm3i9Oj5hwEAL7K4Hp26tgj5DDr2Yj4EsqPV1Uye8BynjLnghQzDpZSh0DXvLS1aJuyi3wYXtmLNcvUivZUC+aKG8m/nRIg5DI3OFK2u2BSLxAfBTvf0ItO7UIkbVrzZxk7Eu4o5s587GPPhZxL8zhoBnkslx3F9ihW25ylSKLv+1ZzXBhT3cdCLvAofoUkGwTZF/FKEBx02wrwVBmqIPMGS8FlXz6FnqbNnhJQ1EQO6/nkByjCaJIcYzjDBchldGV02MyUQ1Q663BSdWQ6RhrhPBWqA/BhKqog="