language: python
if: type=push
python:
- 3.5
rvm:
- 2.0.0

services:
- docker

before_install:
- if [ -n "${STOREPASS}" ]; then openssl aes-256-cbc -K $encrypted_d617236a007d_key -iv $encrypted_d617236a007d_iv -in Input_keystore.keystore.enc -out Input_keystore.keystore -d -md md5; fi;
- if [ -n "${STOREPASS}" ]; then openssl aes-256-cbc -k $MERGINSECRETS_DECRYPT_KEY -in app/merginsecrets.cpp.enc -out app/merginsecrets.cpp -d -md md5; fi;
- gem update bundler
- gem --version
- pip3 install dropbox

script:
- export SDK_VERSION=android-15
- export INPUT_SDK=lutraconsulting/input-sdk:${SDK_VERSION}
- docker pull ${INPUT_SDK}
- docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-${ARCH}" -e "ARCH=${ARCH}" -e "STOREPASS=${STOREPASS}" -e "KEYNAME=${KEYNAME}" -e "VERSION=${TRAVIS_TAG}" ${INPUT_SDK} /usr/src/input/scripts/docker-build.sh
- "./scripts/upload-artifacts.sh"

jobs:
  include:
  - stage: build
    name: "Build armeabi-v7a"
    env:
    - ARCH=armeabi-v7a
  - stage: build
    name: "Build arm64-v8a"
    env:
    - ARCH=arm64-v8a
