language: python
python:
- 3.5
rvm:
- 2.0.0
services:
- docker
env:
  global:
    - secure: "tM8jAXw6JIrglXsJEv/I6I4NEzgv+evNfowzckMqdzLWJ7Huog4f1T4VxDRHWpca+g+XjE+Qto6W6s5C35Lv74runQn7VtkeiSKCRDk43LbE6X5RySthn/Q1q3iO1V5GShWYtaHmBKueUZIX+o+xUZSmsJ/Ix+TXAERSg+E9ARWCXvdv94aJG0jnmX4d974vxntJO/+6tW9q+S24tZ/LhSNCfGg7E8rPlY5eqaBsZkEqV2SL87QVCQAGA5srqFLf6SqSl+9/v7rukmXQC0uQ2C4GWbyba7PRXvsm5wq/crVjiuT8sw22m4nC/RKEMDYVw2cZdmxb6TDJDnmC+5le1QqmkFtOI8l0IWLDnF1TSp3PlpvnhTb6QV2t/hINi/xF/yomiKPY8IR4OLlNhhoFpYXrE+Inju/9vTLvDwGUwPSn4g4OejIkxF8XGlcBfmMuS4xQWO6Pij8zposFz6Nh7WbW9t7y3ETNoWaNxSbANd9WOptxWQJHmbI4xMY77XcDcOeYtDCpKJFyaKCxHVmwcl2UZnuEaijSKNtt+xJgRGDg0nkyyJd6zueOC4a++owa/+es7lBNU4Wg810B955JZJQzvGQ4sCE2rRNkNZQuRS/DBRTJ0HsMzEWqP3kvDZPZiU4l+LBg3Y61KD+SaGN3Y43Mo/iPyuglD970qfN3B9s="
    - secure: "UcKraI5hTd7sGaumI1ifUp+gmmiYELalaOpmmusn9tVqInN7fCR98qjhizdb07j1aOrSEb0MJZX381M4226PKkMhBqj74mwo7ga80AAOZwhzM2AjVEV2ssVEhgMEACLgxujcNg57+r9kSIG7HVFfYbiZAKD2qPmtP69Hrd/D/2EKyCfNtlG7lw9Io2yemUGR5UUbQSxv6t1yPEHj7rAuoeRpGWhMXKcTXt98lk1lFkPI6Igda1wXZQfbbReUbtDmr6v4ffGN5Hd1zkZIECPIjlwYB3qXz3x2XrtIJV9LNq1gH6Fk5TmZNYtZSJZwVxPwvCdr+83zw4gepjKYTl0u56wUoRy4LrafPvN9emFRUb6VyNQ94hJrVAD2+hTx7GJLX95n/Bq2/u0+87Le62d3IQw205NHgPOPa4ITtH/gtdMXsWOSj8ov4ydRNAqYvrWN/PZyVGluokhTUC2nWule7POgWVr5BBdhbz/wliGFNGZcMeIPOJqKc49lPWvYF2MCbTT13FkB7lUcT9stj39HtqTgeQqLOsOM+InMRvww3PG/otZpvS6X/+wZx4Z/U0u/Zrir2XuUFlX105JIdekW3fQmySsTU+Mk85rGTk2q5o9SVJzVkilDFSHIcG2/N/ueO/tckpX0ZsTw+LVl+6If5aYBthJZJKTrjsIRQ6EpGkU="
before_install:
- gem update --system
- gem --version
- pip3 install dropbox
script:
- export OSGEO4A_SDK=opengisch/qfield-sdk:20190221
- docker pull ${OSGEO4A_SDK}
- docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-${ARCH}" -e "ARCH=${ARCH}"
  -e "VERSION=${TRAVIS_TAG}" ${OSGEO4A_SDK} /usr/src/input/scripts/docker-build.sh
- "./scripts/upload-artifacts.sh"
jobs:
  include:
  - stage: build
    name: build ARMv7
    env:
    - ARCH=armv7