version: 2
jobs:
  build:
    docker:
      - image: debian:sid
        environment:
          CIRCLECI: 1
    steps:
      - checkout
      - run:
          name: Install
          command: 'apt-get update; apt-get install astyle'
      - run:
          name: Code Style
          command: ./scripts/check_all.bash
