name: Android
on: [push]
env:
  SDK_VERSION: android-19
  STOREPASS: ${{ secrets.STOREPASS }}

jobs:
  android_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8aarm64-v8a]
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run:
          sudo apt update && sudo apt install -y pip3 gem openssl docker
          gem update bundler
          pip3 install dropbox
          gem --version
          python3 --version

      - name: Extract Mergin API_KEY
        env:
          MERGINSECRETS_DECRYPT_KEY: ${{ secrets.MERGINSECRETS_DECRYPT_KEY }}
        run: |
          if [ -n "${STOREPASS}" ]; then openssl aes-256-cbc -k $MERGINSECRETS_DECRYPT_KEY -in app/merginsecrets.cpp.enc -out app/merginsecrets.cpp -d -md md5; fi;


      - name: Extract GPS keystore
        env:
          INPUTKEYSTORE_DECRYPT_KEY: ${{ secrets.INPUTKEYSTORE_DECRYPT_KEY }}

        run: |
          if [ -n "${STOREPASS}" ]; then openssl aes-256-cbc -k $INPUTKEYSTORE_DECRYPT_KEY -in Input_keystore.keystore.enc -out Input_keystore.keystore -d -md md5; fi;

      - name: Build and Upload
        env:
          ARCH: ${{ matrix.arch }}
          DROPBOX_TOKEN: ${{ secrets.INPUTAPP_BOT_DROPBOX_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.INPUTAPP_BOT_GITHUB_TOKEN }}

        run: |
          if  [[ ${{ github.ref }} == refs/tags/* ]]
          then
              GIT_TAG="$(clean ${var_to_use/refs\/tags\//})"
          else
              GIT_TAG=""
          fi

          docker pull lutraconsulting/input-sdk:${SDK_VERSION}
          docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-${ARCH}" -e "ARCH=${ARCH}" -e "STOREPASS=${STOREPASS}" -e "VERSION=${GIT_TAG}" lutraconsulting/input-sdk:${SDK_VERSION} /usr/src/input/scripts/docker-build.sh
          ./scripts/upload-artifacts.sh
