name: Auto Tests
on: [push]
env:
  TEST_MERGIN_URL: https://test.dev.cloudmergin.com/
  TEST_API_USERNAME: test_inputapp
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  QT_VERSION: 5.14.2
  QGIS_DEPS_VERSION: 0.4.0
  INPUT_SDK_HASH: owte1n3uebt4jl1
  INPUT_SDK_VERSION: 1

jobs:
  tests:
    if: github.repository == 'lutraconsulting/input'
    runs-on: macos-latest
    steps:
      - name: Checkout Input
        uses: actions/checkout@v2
        with:
          path: input

      - name: install brew deps
        run: |
          brew install lcov ruby
          sudo gem install coveralls-lcov

      - name: download qt
        run: |
          ROOT=`pwd`
          wget https://qgis.org/downloads/macos/deps/qt-${QT_VERSION}.tar.gz
          sudo mkdir -p /opt/Qt/${QT_VERSION}/clang_64
          cd /opt/Qt/${QT_VERSION}/clang_64
          sudo tar -xvzf $ROOT/qt-${QT_VERSION}.tar.gz

      - name: download qgis-deps
        run: |
          ROOT=`pwd`
          wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz
          sudo mkdir -p /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          cd /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          sudo tar -xvzf $ROOT/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz

      - name: download input-sdk
        run: |
          ROOT=`pwd`
          wget https://www.dropbox.com/s/${INPUT_SDK_HASH}/input-sdk-qt-${QT_VERSION}-deps-${QGIS_DEPS_VERSION}-mac-${INPUT_SDK_VERSION}.tar.gz?dl=0
          mv $ROOT/input-sdk-qt-${QT_VERSION}-deps-${QGIS_DEPS_VERSION}-mac-${INPUT_SDK_VERSION}.tar.gz $ROOT/input-sdk.tar.gz
          sudo mkdir -p ${ROOT}/sdk
          cd ${ROOT}/sdk
          sudo tar -xvzf $ROOT/input-sdk.tar.gz
          ls ${ROOT}/sdk

      - name: build Input
        run: |
          export ROOT_DIR=`pwd`
          cp input/scripts/ci/config.pri input/app/config.pri

          mkdir -p build-Input
          cd build-Input
          /opt/Qt/${QT_VERSION}/clang_64/bin/qmake \
            ../input/app/input.pro \
            CONFIG+=debug \
            CONFIG+=qtquickcompiler

          make -j $(sysctl -n hw.ncpu)
        
      - name: run tests
        run: |
          ROOT_DIR=`pwd`
          cd build-Input/Input.app/Contents/MacOS
          install_name_tool -add_rpath /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/lib/
          install_name_tool -add_rpath $ROOT_DIR/build-geodiff/

          ./Input --test

      - name: submit coveralls
        run: |
          cd build-Input/Input.app/Contents/MacOS
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/tests/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          coveralls-lcov coverage.info
