name: Auto Tests
on: [push]
env:
  TEST_MERGIN_URL: https://test.dev.cloudmergin.com/
  TEST_API_USERNAME: test_inputapp
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  QT_VERSION: 5.14.2
  QGIS_DEPS_VERSION: 0.4.0
  QGIS_COMMIT: da042bb61dc7447b41b021838efe42d08b31cdd8
  GEODIFF_VERSION: release-0.8.2
  ROOT_DIR: .

jobs:
  tests:
    if: github.repository == 'lutraconsulting/input'
    runs-on: macos-latest
    steps:
      - name: Checkout Input
        uses: actions/checkout@v2
        with:
          path: input

      - name: Checkout QGIS
        uses: actions/checkout@v2
        with:
          repository: qgis/QGIS
          path: qgis

      - name: Checkout geodiff
        uses: actions/checkout@v2
        with:
          repository: lutraconsulting/geodiff
          path: geodiff

      - name: install brew deps
        run: |
          brew install lcov ruby
          sudo gem install coveralls-lcov

      - name: download qgis-deps
        run: |
          wget https://qgis.org/downloads/macos/deps/qt-${QT_VERSION}.tar.gz
          wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz
          ls .
          pwd

      - name: install qgis-deps
        run: |
          ROOT=`pwd`
          sudo mkdir -p /opt/Qt/${QT_VERSION}/clang_64
          cd /opt/Qt/${QT_VERSION}/clang_64
          sudo tar -xvzf $ROOT/qt-${QT_VERSION}.tar.gz

          sudo mkdir -p /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          cd /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          sudo tar -xvzf $ROOT/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz

      - name: build geodiff
        run: |
          mkdir -p build-geodiff
          mkdir -p Applications
          cd build-geodiff

          PATH=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/bin:$PATH \
          cmake \
                -DCMAKE_INSTALL_PREFIX:PATH=../Applications \
                -DCMAKE_BUILD_TYPE=Release \
                -DWITH_INTERNAL_SQLITE3:BOOL=FALSE \
                -DSQLite3_INCLUDE_DIR:PATH=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/include \
                -DSQLite3_LIBRARY=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/lib/libsqlite3.dylib \
                -DENABLE_TESTS=FALSE \
                -DBUILD_TOOLS=OFF \
                 ../geodiff/geodiff

          make -j $(sysctl -n hw.ncpu)
          make install

      - name: build QGIS
        run: |
          mkdir -p build-QGIS
          mkdir -p Applications
          cd build-QGIS

          PATH=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/bin:$PATH \
          cmake -DQGIS_MAC_DEPS_DIR=/opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage \
                -DCMAKE_PREFIX_PATH=/opt/Qt/${QT_VERSION}/clang_64 \
                -DCMAKE_BUILD_TYPE=Debug \
                -DWITH_BINDINGS=FALSE \
                -DWITH_DESKTOP=OFF \
                -DWITH_ANALYSIS=OFF \
                -DDISABLE_DEPRECATED=ON \
                -DWITH_QTWEBKIT=OFF \
                -DWITH_GRASS=OFF \
                -DWITH_QTMOBILITY=OFF \
                -DWITH_QUICK=ON \
                -DCMAKE_INSTALL_PREFIX:PATH=../Applications \
                -DENABLE_QT5=ON \
                -DENABLE_TESTS=OFF \
                -DWITH_INTERNAL_QWTPOLAR=OFF \
                -DWITH_QWTPOLAR=OFF \
                -DWITH_GUI=OFF \
                -DWITH_APIDOC=OFF \
                -DWITH_ASTYLE=OFF \
                -DWITH_QT5SERIALPORT=OFF \
                -DWITH_QSPATIALITE=OFF \
                -DWITH_3D=FALSE \
                -DWITH_QGIS_PROCESS=OFF \
                -DQGIS_MACAPP_BUNDLE=-1 \
                 ../qgis

          make -j $(sysctl -n hw.ncpu)
          make install

      - name: build Input
        run: |
          cp input/scripts/ci/config.pri input/app/config.pri

          mkdir -p build-Input
          cd build-Input
          /opt/Qt/${QT_VERSION}/clang_64/bin/qmake \
            ../input/app/input.pro \
            CONFIG+=release \
            CONFIG+=qtquickcompiler

          make -j $(sysctl -n hw.ncpu)
        
      - name: run tests
        run: |
          cd build-Input
          ./input --test

      - name: submit coveralls
        run: |
          cd build-Input
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/tests/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          coveralls-lcov coverage.info
