name: Code Layout
on: [push]
env:
  QT_VERSION: 6.2.0
jobs:
  code_style_cpp:
    name: C++ code convention check
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    steps:
      - name: Install astyle
        run: |
          sudo apt-get install astyle

      - uses: actions/checkout@v2

      - name: Run astyle check
        run: |
          ./scripts/format_cpp.bash

  code_style_qml:
    name: QML code convention check
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: macos-latest
    needs: code_style_cpp # Run when cpp is finished to save some time if cpp would fail
    steps:

    # Cache qt
      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v2-${{ env.QT_VERSION }}-mac

      - name: Install Qt6
        uses: jurplel/install-qt-action@v2 # automatically chooses mac desktop based on env
        with:
          version: ${{ env.QT_VERSION }}
          dir: ${{ github.workspace }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: false

      - uses: actions/checkout@v2

      - name: Run style check
        run: |
          Path=$PATH:${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/macos/bin
          ./scripts/format_qml.bash
