name: Code Layout
on: [push]
jobs:
  code_style_cpp:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    steps:
      - name: Install astyle
        run: |
          sudo apt-get install astyle

      - uses: actions/checkout@v2

      - name: Run astyle check
        run: |
          ./scripts/check_all.bash

  code_style_qml:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: macos-latest
    needs: code_style_cpp # Run when cpp is finished to save some time if cpp would fail
    steps:

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt6
        uses: jurplel/install-qt-action@v2 # automatically chooses mac desktop based on env
        with:
          version: '6.2.1'
          dir: '../Qt'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: false

      - uses: actions/checkout@v2

      - name: Run style check
        run: ./scripts/qmlstyle.bash
