name: Gallery App
on:
  push:
    paths:
    - 'app/qml/**'
    - 'app/qmlV2/**'
    - 'gallery/**'
    - '.github/workflows/gallery.yml'

  release:
    types:
      - published

concurrency:
  group: ci-${{github.ref}}-gallery
  cancel-in-progress: true

jobs:
  gallery_build:
    if: ( github.repository == 'MerginMaps/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      QT_VERSION: '6.5.2'
      GITHUB_TOKEN: ${{ secrets.INPUTAPP_BOT_GITHUB_TOKEN }}
      CACHE_VERSION: 0
      XC_VERSION: ${{ '14.2' }} # macos-only

    steps:
      - uses: actions/checkout@v3

      - name: Select latest Xcode
        if: matrix.os == 'macos-latest'
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-v${{ env.CACHE_VERSION}}-${{ env.QT_VERSION }}-gallery

      - name: Configure Gallery App
        run: |
            mkdir -p ${{ github.workspace }}/install-gallery
            mkdir -p ${{ github.workspace }}/build-gallery
            cd ${{ github.workspace }}/build-gallery

            cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${QT_VERSION}/macos \
              -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/install-gallery \
              -GNinja \
              -S ../gallery \
              -B ./
      
      - name: Build Gallery App
        run: |
            cd ${{ github.workspace }}/build-gallery
            ninja
            ninja install
            ls -la ${{ github.workspace }}/install-gallery

      - name: Prepare artefacts (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd ${{ github.workspace }}/install-gallery
          tar -czf ${{ github.workspace }}/merginmaps-gallery-${{ matrix.os }}.tar.gz

      - name: Prepare artefacts (macos)
        if: matrix.os == 'macos-latest'
        run: |
          cd ${{ github.workspace }}/install-gallery
          tar -czf ${{ github.workspace }}/merginmaps-gallery-${{ matrix.os }}.tar.gz MerginMapsGallery.app/

      - name: Prepare artefacts (windows)
        if: matrix.os == 'windows-latest'
        run: |
          

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/merginmaps-gallery-${{ matrix.os }}.tar.gz
          name: Mergin Maps Gallery ${{ matrix.os }}

