name: linux Build
on:
  push:
    paths:
    - 'app/**'
    - 'core/**'
    - 'scripts/**'
    - '.github/workflows/linux.yml'

  release:
    types:
      - published

env:
  CCACHE_DIR: ~/.ccache
  INPUT_SDK_VERSION: ubuntu-2204-20221117-103
  QT_VERSION: '6.4.1'
  CACHE_VERSION: 0
      
concurrency:
  group: ci-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  linux_build:
    if: ( github.repository == 'MerginMaps/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Input
        uses: actions/checkout@v2
        with:
          path: input

      - name: Install Build Dependencies
        run: |
            sudo apt-get update -y                    
            sudo apt-get install -y libcurl4-gnutls-dev bison ca-certificates ccache cmake cmake-curses-gui dh-python expect flex flip \
                            git graphviz libexiv2-dev libexpat1-dev libfcgi-dev libgeos-dev libgeos++-dev libwebp-dev \
                            libgsl-dev libfreexl-dev libpq-dev libprotobuf-dev \
                            libspatialindex-dev libsqlite3-dev libyaml-tiny-perl \
                            libzip-dev libzstd-dev lighttpd locales ninja-build \
                            pkg-config poppler-utils protobuf-compiler python3-all-dev \
                            spawn-fcgi xauth xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable xvfb \
                            gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
                            gstreamer1.0-plugins-ugly gstreamer1.0-x libgstreamer-gl1.0-0 libgstreamer-plugins-base1.0-0 \
                            libgstreamer-plugins-good1.0-0 libgstreamer1.0-0
            
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: 'false'
          modules: 'qtsensors qtconnectivity qt5compat qtmultimedia qtpositioning qtshadertools'
          dir: ${{ github.workspace }}
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-v0-${{ env.QT_VERSION }}-lnx

      - name: Extract Mergin API_KEY
        env:
          MERGINSECRETS_DECRYPT_KEY: ${{ secrets.MERGINSECRETS_DECRYPT_KEY }}
        run: |
          cd input/core/
          openssl \
            aes-256-cbc -d \
            -in merginsecrets.cpp.enc \
            -out merginsecrets.cpp \
            -k "$MERGINSECRETS_DECRYPT_KEY" \
            -md md5

      # CCache
      - name: Prepare build cache for pull request
        uses: pat-s/always-upload-cache@v2.1.5
        if: github.event_name == 'pull_request'
        with:
          path: ${{ env.CCACHE_DIR }}
          key: build-linux-ccache-${{ github.actor }}-${{ github.head_ref }}-${{ github.sha }}
          # The head_ref or source branch of the pull request in a workflow run.
          # The base_ref or target branch of the pull request in a workflow run.
          restore-keys: |
            build-linux-ccache-${{ github.actor }}-${{ github.head_ref }}-
            build-linux-ccache-refs/heads/${{ github.base_ref }}-
            build-linux-ccache-refs/heads/master-

      - name: Prepare build cache for branch/tag
        # use a fork of actions/cache@v2 to upload cache even when the build or test failed
        uses: pat-s/always-upload-cache@v2.1.5
        if: github.event_name != 'pull_request'
        with:
          path: ${{ env.CCACHE_DIR }}
          # The branch or tag ref that triggered the workflow run. For branches this in the format refs/heads/<branch_name>, and for tags it is refs/tags/<tag_name>
          key: build-linux-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            build-linux-ccache-${{ github.ref }}-
            build-linux-ccache-refs/heads/master-

      - name: Install ccache
        run: |
          mkdir -p ${CCACHE_DIR}
          ccache --set-config=max_size=2.0G
          ccache -s

      # Input SDK
      - name: Cache Input-SDK
        id: cache-input-sdk
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/input-sdk
          key: ${{ runner.os }}-input-sdk-v0-${{ env.INPUT_SDK_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install Input-SDK
        if: steps.cache-input-sdk.outputs.cache-hit != 'true'
        run: |
          wget -O \
            ${{ github.workspace }}/input-sdk.tar.gz \
            https://github.com/MerginMaps/input-sdk/releases/download/${{ env.INPUT_SDK_VERSION }}/input-sdk-${{ env.INPUT_SDK_VERSION }}.tar.gz
          mkdir -p ${{ github.workspace }}/input-sdk
          cd ${{ github.workspace }}/input-sdk
          tar -xvzf ${{ github.workspace }}/input-sdk.tar.gz

      # Build Input App          
      - name: build Input
        run: |
          mkdir -p install-Input
          mkdir -p build-Input
          cd build-Input

          cmake \
             -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${QT_VERSION}/macos \
             -DCMAKE_INSTALL_PREFIX:PATH=../install-Input \
             -DUSE_SERVER_API_KEY=TRUE \
             -DINPUT_SDK_PATH=${{ github.workspace }}/input-sdk \
             -DQGIS_QUICK_DATA_PATH=${{ github.workspace }}/input/app/android/assets/qgis-data \
             -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
             ..
             
          make

      - name: Get TimeStamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: package Input
        run: |
          INPUT_TAR=input-${{ env.INPUT_SDK_VERSION }}-${{ steps.time.outputs.time }}-${{ github.run_number }}.tar.gz
          echo "INPUT_TAR=${INPUT_TAR}" >> $GITHUB_ENV
          cd ${{ github.workspace }}/build-Input
          tar -c -z -f ${{ github.workspace }}/${INPUT_TAR} ./Input

      - name: Upload Sdk in Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/${{ env.INPUT_TAR }}
