name: QgsQuick
on:
  push:
    paths:
    - 'qgsquick/**'
    - 'scripts/**'
    - 'app/**'
    - '.github/workflows/qgsquick.yml'

  release:
    types:
      - published

env:
  QGIS_COMMIT_HASH: 2b6121f9b98c35b2cf453dd879e3553b97f943c9

jobs:
  qgsquick_up_to_date:
    if: ( github.repository == 'MerginMaps/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download qgis
        run: |
          git clone https://github.com/qgis/QGIS.git --depth 1
          cd QGIS
          git fetch --depth 1 origin ${QGIS_COMMIT_HASH}
          git checkout FETCH_HEAD
          cd ..

      - name: run check the qgsquick is up-to-date
        run: |
          ./scripts/copy_qgsquick.bash QGIS/
